# DO NOT REMOVE THIS
theme = "hugo-theme-codex" 
publishDir = "docs"
# Override these settings with your own
title = "bunbunjin"
languageCode = "ja"
baseURL = "https://bunbunjin.gihub.io/portfolio.github.io"
copyright = "© {year}"
canonifyrls = true

# Add your Disqus shortname here.
# disqusShortname = "aaaaa"

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = "" 
# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  twitter = "https://twitter.com/bunbunjin_aisu"
  github = "https://github.com/bunbunjin"
  # email = "mailto:<your email>"
  # mastodon = "https://mastodon.social/@nickname"
 facebook = "https://facebook.com/bunbunjin.aisu"
  # gitlab = "https://gitlab.com/bunbunjin"
  # instagram = "https://instagram.com/<your handle>"
  # linkedin = "<link to your profile>"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Mastodon", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["Twitter", "GitHub", "Facebook"]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = true
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "About"
  name = "About"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "Blog"
  name = "Blog"
  title = "Blog"
  url = "/blog"

[[menu.main]]
  identifier = 'profile'
  name = 'Profile'
  title = 'profile'
  url = '/profile'

[[menu.main]]
  identifier = 'Deliverable'
  name = 'Opus'
  title = 'Opus'
  url = '/Opus'
